#pragma config(Motor,  port1,           Spin,          tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           LeftFront,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           LeftBack,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           RigthFront,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           RightBack,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int Channel3;
int Channel4;
int threshold = 10;

void deadZoneCheck()
{

    if(abs(vexRT[Ch3]) > threshold)
        Channel3 = vexRT[Ch3];
    else
        Channel3 = 0;

    if(abs(vexRT[Ch4]) > threshold)
        Channel4 = vexRT[Ch4];
    else
        Channel4 = 0;

}

task main()
{
	while (true){

		deadZoneCheck();
		motor[LeftBack]  = (-Channel3 - Channel4)/2;  // (y + x)/2
 	 	motor[LeftFront]  = (-Channel3 - Channel4)/2;  // (y + x)/2
 	 	motor[RigthFront] = (-Channel3 + Channel4)/2;  // (y - x)/2
 	 	motor[RightBack] = (-Channel3 + Channel4)/2;  // (y - x)/2

 	 	if(vexRT[Btn6U] == 1){						//Function for Spinning
 	 			motor[port1] = 35;
 	}else{
 	 			motor[port1] = 0;
 	 		}
	}

}
